### ISSUE TITLE
Controlling which fields are shown in the seach box

### ISSUE THREAD

**Issue by dave7777** [running-coder/jquery-typeahead#363]
Hello 
I have two columns of data and when I scroll up and down the results both of these column elements are MERGED into one an displayed in the search box - where I can disable first column from showing in the search box ?
I have this fillde but it works OK
http://jsfiddle.net/Line7/vw05enbj/
Dave

**Comment by running-coder** [comment]
Hey @dave7777,  not sure I understand the issue. Could you add screenshot or more details?

**Comment by dave7777** [comment]
thank you....here is the screenshot of the menu - as you can see both columns are merged 
<a href="http://tinypic.com?ref=2mc91d5" target="_blank"><img src="http://i64.tinypic.com/2mc91d5.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by running-coder** [comment]
Yea this is considered as a "result row"

**Comment by dave7777** [comment]
can it be limited to second column items only?

**Comment by running-coder** [comment]
this was added in 2.8.0
>templateValue: null,    // Set the input value template when an item is clicked

http://www.runningcoder.org/jquerytypeahead/documentation/#options-templateValue

would this help?

**Comment by dave7777** [comment]
thank you Tom
I have this script....I added the name of the first column into templateValue but it does not work - can you please take a look?


 ```
<form>
        <div class="typeahead__container">
            <div class="typeahead__field">

            <span class="typeahead__query">
                <input class="js-typeahead-input"
                       name="q"
                       type="search"
                       placeholder="Search"
                       autofocus
                       autocomplete="off">
            </span></div>
        </div>
    </form>
</div>

<script>

  var myData = [    ];

   $.typeahead({
  input: ".js-typeahead-input",
  minLength: 1,
  maxItemPerGroup: 20,
  maxItem: 20,
  correlativeTemplate: true,
  templateValue: "{{name}}",
  emptyTemplate: 'No result for "{{query}}"',
  source: {
    myGroup: {
	ajax: {
            url: 'search/src/data2.json'
        }, 
      display: ['name', 'descr'] ,
      href: "{{link}}",
       template: '<span class="typeahead__column">{{name}}</span><span class="typeahead__column">{{descr}}</span>'
    }
  },
  group: {
                key: "category",
                template: function (item) {

                    var category = item.category;
                  

                    return category;
                }
            },
  
    dropdownFilter: [{
                key: 'category',
                template: '{{category}}',
        
            }],
            
  callback: {
    onSubmit: function (node, form, item, event) {
      var href;

      if (this.result.length === 1) {
        href = this.result[0].link;
      } else {
        console.log(this.source)

        for (var i=0, ii=this.source.myGroup.length; i<ii; ++i){
          if (this.query.toLowerCase() === this.source.myGroup[i].name.toLowerCase()) {
            href = this.source.myGroup[i].link
            break;
          }
        }
      }

      if (href) {
        event.preventDefault();
        window.location.href = href;
      }
    }
  }
});
</script>



```

**Comment by dave7777** [comment]
can you please check this code Tom?

**Comment by running-coder** [comment]
hey @dave7777, it works for me using your configuration

```javascript
var myData = [{
    name: 'hi',
    descr: 'descr'
},
    {
        name: 'hey',
        descr: 'descr'
    }];

$.typeahead({
    input: ".js-typeahead-input",
    minLength: 1,
    maxItemPerGroup: 20,
    maxItem: 20,
    correlativeTemplate: true,
    templateValue: "{{name}}",
    emptyTemplate: 'No result for "{{query}}"',
    source: {
        myGroup: {
            data: myData, // replaced this for testing
            display: ['name', 'descr'] ,
            href: "{{link}}",
            template: '<span class="typeahead__column">{{name}}</span>, <span class="typeahead__column">{{descr}}</span>'
        }
    },
```
![screen shot 2017-07-31 at 8 25 33 am](https://user-images.githubusercontent.com/7377382/28777625-0520825c-75ca-11e7-80a5-1237061953a7.png)
![screen shot 2017-07-31 at 8 26 03 am](https://user-images.githubusercontent.com/7377382/28777632-073b880c-75ca-11e7-92ae-6a1f49c5b57d.png)

**Comment by dave7777** [comment]
Thank you for your wonderful help Tom....Sorry to delayed feedback - was reinstalling windows....
Here is the detailed side my side report comparing this code and mine:

https://jsfiddle.net/b66ve8o3/

as you will notice it is mostly same as yours -I wonder if this templateValue is nto workign because I am using other complex features afterwards/retreiving the results via AJAX?

Can you please take a look?

Thank you again!

Dave

**Comment by dave7777** [comment]
I noticed you have comma here:
       template: '<span class="typeahead__column">{{name}}</span>, <span class="typeahead__column">{{descr}}</span>'

but adding a comma to this line of mine disrupted the results...:((((

 template: '<span class="typeahead__column">{{name}}</span><span class="typeahead__column">{{descr}}</span>'

**Comment by running-coder** [comment]
Was using `, ` in the template so the terms would be seperated ;). I've added a fiddle. https://jsfiddle.net/runningcoder/rauxqosd/2/

**Comment by dave7777** [comment]
thank you so much Tom! 👍 

I see you are using
 templateValue: "{{name}}",

and still you have two names from each column shown when I scroll down with the keyboard.....not sure why this code is not working:

 templateValue: "{{name}}",

can you please take a look?

**Comment by dave7777** [comment]
У вас есть что то из этого

http://www.crucial.com/usa/en/compatible-upgrade-for/HP---Compaq/hp-z420-workstation

ОНИ купили производителя РАМ ELPIDA - может это вообще будут родные для
моей памяти (ELPIDA )?

**Comment by dave7777** [comment]
http://www.crucial.com/usa/en/hp-z420-workstation/CT2896659
http://www.crucial.com/usa/en/hp-z420-workstation/CT4270153

**Comment by running-coder** [comment]
oh! this is a mistake, I've forgot to consider the `templateValue` when using the navigation arrows and not only the click 👍

**Comment by dave7777** [comment]
thank you.......do you think there can be a quick fix for this? - maybe even a space between the results (I have two columns) on KEYBOARD SCROLL DOWN OR UP?

**Comment by dave7777** [comment]
I mean in your example it has the SPACE between results when scrolling - how did you do that?:)

**Comment by dave7777** [comment]
maybe my results are merged on scroll down and up because I have this css:

```
		.typeahead__column {
  width: 30%;
  display: inline-block;
}

.typeahead__column:last-child {
	  width: 70%;
  text-align: left;
}

	</style>
```

**Comment by dave7777** [comment]
I uploaded all of your code in my website and it still does nto show space between the results:

<a href="http://tinypic.com?ref=25fobgl" target="_blank"><img src="http://i64.tinypic.com/25fobgl.png" border="0" alt="Image and video hosting by TinyPic"></a>

MAYBE SOME CCS style might be preventing this from showing?

**Comment by running-coder** [comment]
oh.. took me a while to remember... that's a change from #351, not yet released on `master`...

**Comment by dave7777** [comment]
Thank you Tom - meaning the current code will not support this?

**Comment by running-coder** [comment]
I've added a commit to fix the arrow and tab navigation on the `develop` branch, can youvalidate that this is solved?

**Comment by dave7777** [comment]
when do you plan to release 2.9.0 ?

**Comment by running-coder** [comment]
2.9.0 is not ready to be released, there are a bunch of things I need to figure out before... if you are using NPM you can always use the commit hash to pull from the registry

**Comment by dave7777** [comment]
Hello Tom - I am preparing to launch a special platform based on our search script - this issue still shwos up whn scrollign the serach box - can it be corrected now?
